"""empty message

Revision ID: d74f6625919e
Revises: 956fb3147705
Create Date: 2024-09-18 12:43:40.988635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd74f6625919e'
down_revision: Union[str, None] = '956fb3147705'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('user_author', sa.Boolean(), nullable=False),
    sa.Column('id_chat', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_chat'], ['chats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('index_chat', 'messages', ['id_chat'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('index_chat', table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
